export const AUTH_USER = 'AUTH_USER';
export const AUTH_REDIRECT = 'AUTH_REDIRECT';
export const LOGIN_PANEL = 'LOGIN_PANEL';
export const RECOVER_EMAIL_PANEL = 'RECOVER_EMAIL_PANEL';
export const RECOVER_EMAIL_SUCCESS_PANEL = 'RECOVER_EMAIL_SUCCESS_PANEL';
export const RECOVER_PASSWORD_PANEL = 'RECOVER_PASSWORD_PANEL';
export const RECOVER_PASSWORD_SUCCESS_PANEL = 'RECOVER_PASSWORD_SUCCESS_PANEL';
export const USER_CHECKWORD_PANEL = 'USER_CHECKWORD_PANEL';
