export const SET_GB_FILTER = 'SET_GB_FILTER';
export const SET_FR_FILTER = 'SET_FR_FILTER';
export const SET_GB_LISTING = 'SET_GB_LISTING';
export const LOADING_GB_LISTING = 'LOADING_GB_LISTING';
export const UPDATE_GB_OPTIONS = 'UPDATE_GB_OPTIONS';
export const SET_GB_OPTIONS = 'SET_GB_OPTIONS';
