export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SET_PATCH_NOTES = 'SET_PATCH_NOTES';
export const SET_STICKERS = 'SET_STICKERS';
export const SET_USER = 'SET_USER';
export const STICKERS_UPDATED = 'STICKERS_UPDATED';
export const TRIGGER_NOTIFICATIONS = 'TRIGGER_NOTIFICATIONS';
export const TRIGGER_PATCH_NOTES = 'TRIGGER_PATCH_NOTES';
export const TRIGGER_STICKERS = 'TRIGGER_STICKERS';

