export const RECOVER_EMAIL = 'RECOVER_EMAIL';
export const RECOVER_EMAIL_SUBMIT_ERROR = 'RECOVER_EMAIL_SUBMIT_ERROR';
export const RECOVER_EMAIL_SUBMIT_START = 'RECOVER_EMAIL_SUBMIT_START';
export const RECOVER_EMAIL_SUBMIT_SUCCESS = 'RECOVER_EMAIL_SUBMIT_SUCCESS';
export const RECOVER_EMAIL_SUBMIT_TOUCH = 'RECOVER_EMAIL_SUBMIT_TOUCH';
