const fakeData = [
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 20)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Раскрученная клининговая компания с корпоративными клиентами',
    category: 'Рекламные агентства',
    location: 'СБП',
    price: '850 000 000',
    profit: '280 000',
    broker: 'Закерьяев М.',
    dealer: 'Закерьяев М.',
    created: 'вчера',
    lastUpdate: '3 дня',
    viewed: '1145',
    likes: '45%',
    comments: '2',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Федеральная сеть островных кафе в крупных ТРК с высокой проходимостью',
    category: 'Бизнес-школы',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: '2 февраля',
    lastUpdate: '12 дней',
    viewed: '321',
    likes: '94%',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
  {
    id: 129478,
    img: `https://unsplash.it/40?image=${Math.floor(Math.random() * 10)}`,
    name: 'Частный детский сад в Московском районе',
    category: 'Наркологические клиники',
    location: 'СБП',
    price: '1 000 000 000',
    profit: '250 000 000',
    broker: 'Дубровин Н.',
    dealer: 'Сидачев К.',
    created: 'сегодня',
    lastUpdate: '1 день',
    viewed: '289',
    likes: '87%',
    comments: '1',
  },
];

export default fakeData;
